import Head from 'next/head';
import Image from 'next/image';
import Sidebar from '../components/Sidebar';
import { FaBell, FaUserCircle, FaUserAlt } from 'react-icons/fa';
import { useState } from 'react';

export default function Home() {
  const [toggleDropdown, setToggleDropdown] = useState(false);
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className=''>
        <section className='flex'>
          <div className='w-1/12 z-10'>
            <Sidebar />
          </div>
          <div className='w-11/12'>
            <div className='drop-shadow-md h-44'>
              <div className='flex justify-between items-center bg-white p-4'>
                <div>
                  <div className='flex relative'>
                    <input
                      type='text'
                      name=''
                      id=''
                      className='border border-[#8CD4FD] rounded-xl px-10 py-1'
                      placeholder='Cari Pasien / Nomor MR...'
                    />
                    <FaUserAlt className='absolute top-2 right-2' />
                  </div>
                </div>
                <div className='flex space-x-5 items-center'>
                  <div className='w-[59px] h-[48px]'>
                    <Image
                      // className='items-center'
                      src='/image/User.png'
                      width='100%'
                      height='100%'
                      alt='logo'
                      objectFit='contain'
                    />
                  </div>
                  <div>
                    <button
                      onClick={() => setToggleDropdown(!toggleDropdown)}
                      className='text-white bg-blue-700 hover:bg-blue-800 rounded-lg text-sm px-4 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800'
                      type='button'
                    >
                      Dropdown divider
                    </button>
                    {toggleDropdown && (
                      <div className='fixed z-10 mt-2 h-auto w-26 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600'>
                        <ul className='py-1 text-sm text-gray-700 dark:text-gray-200'>
                          <li>
                            <a
                              href='#'
                              className='block py-2 px-2  text-black hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white'
                            >
                              Dashboard
                            </a>
                          </li>
                          <li>
                            <a
                              href='#'
                              className='block py-2 px-2  text-black hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white'
                            >
                              Settings
                            </a>
                          </li>
                          <li>
                            <a
                              href='#'
                              className='block py-2 px-2  text-black hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white'
                            >
                              Earnings
                            </a>
                          </li>
                        </ul>
                        <div className='py-1'>
                          <a
                            href='#'
                            className='block py-2 px-2 text-sm text-black hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white'
                          >
                            Separated link
                          </a>
                        </div>
                      </div>
                    )}
                  </div>
                  <FaBell />
                  <FaUserCircle />
                </div>
              </div>

              <div className='flex justify-between items-center  bg-white p-4'>
                <div>
                  <div className='flex relative'>
                    <h1>Dashboard</h1>
                    <input
                      type='text'
                      name=''
                      id=''
                      placeholder='FDC Bogor'
                      className='border border-gray-500'
                    />
                    <button>Filter</button>
                  </div>
                </div>
              </div>
            </div>
            <div className='flex gap-2'>
              <div className='w-6/12 grid grid-cols-1 gap-2'>
                <div className='w-full h-[342px] drop-shadow-md  bg-white'>
                  safgasfg
                </div>
                <div className='w-full h-[177px] drop-shadow-md  bg-white'>
                  sgdasg
                </div>
              </div>
              <div className='w-6/12 grid grid-cols-2 gap-2'>
                <div className='w-full h-[168px] drop-shadow-md bg-white'>
                  fas
                </div>
                <div className='w-full h-[168px] drop-shadow-md bg-white'>
                  asfas
                </div>
                <div className='w-full h-[169px] drop-shadow-md bg-white'>
                  fas
                </div>
                <div className='w-full h-[169px] drop-shadow-md bg-white'>
                  asfas
                </div>
                <div className='w-12/12 h-[177px] drop-shadow-md bg-white'>
                  fas
                </div>
                <div className='w-12/12 h-[177px] drop-shadow-md bg-white'>
                  asfas
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
